In [99]:
import pandas as pd
import numpy as np

In [100]:
df = pd.read_csv(r"C:\Users\nidhi\Desktop\NEC\BeijingPM20100101_20151231.csv")
df.head()

No  year  month  day  hour  season  PM_Dongsi  PM_Dongsihuan  \
0   1  2010      1    1     0       4        NaN            NaN   
1   2  2010      1    1     1       4        NaN            NaN   
2   3  2010      1    1     2       4        NaN            NaN   
3   4  2010      1    1     3       4        NaN            NaN   
4   5  2010      1    1     4       4        NaN            NaN   

   PM_Nongzhanguan  PM_US Post  DEWP  HUMI    PRES  TEMP cbwd    Iws  \
0              NaN         NaN -21.0  43.0  1021.0 -11.0   NW   1.79   
1              NaN         NaN -21.0  47.0  1020.0 -12.0   NW   4.92   
2              NaN         NaN -21.0  43.0  1019.0 -11.0   NW   6.71   
3              NaN         NaN -21.0  55.0  1019.0 -14.0   NW   9.84   
4              NaN         NaN -20.0  51.0  1018.0 -12.0   NW  12.97   

   precipitation  Iprec  
0            0.0    0.0  
1            0.0    0.0  
2            0.0    0.0  
3            0.0    0.0  
4            0.0    0.0

In [101]:
df2 = df.dropna()
df2.head()

No  year  month  day  hour  season  PM_Dongsi  PM_Dongsihuan  \
27824  27825  2013      3    5     8       1      117.0          166.0   
27825  27826  2013      3    5     9       1      131.0          165.0   
27826  27827  2013      3    5    10       1      141.0          173.0   
27828  27829  2013      3    5    12       1      169.0          182.0   
27829  27830  2013      3    5    13       1      169.0          169.0   

       PM_Nongzhanguan  PM_US Post  DEWP  HUMI    PRES  TEMP cbwd   Iws  \
27824            140.0       150.0  -6.0  59.0  1019.0   1.0   cv  0.89   
27825            152.0       163.0  -8.0  38.0  1019.0   5.0   cv  1.78   
27826            128.0       172.0  -8.0  31.0  1018.0   8.0   cv  2.67   
27828              3.0       181.0  -9.0  23.0  1017.0  11.0   cv  4.45   
27829              3.0       187.0  -9.0  22.0  1015.0  12.0   cv  5.34   

       precipitation  Iprec  
27824            0.0    0.0  
27825            0.0    0.0  
27826            0.0    0.0  
27828            0.0    0.0  
27829            0.0    0.0

In [102]:
df2.isnull().sum()

No                 0
year               0
month              0
day                0
hour               0
season             0
PM_Dongsi          0
PM_Dongsihuan      0
PM_Nongzhanguan    0
PM_US Post         0
DEWP               0
HUMI               0
PRES               0
TEMP               0
cbwd               0
Iws                0
precipitation      0
Iprec              0
dtype: int64

In [103]:
#df3 = (df2- df2.min())/(df2.max()-df2.min())
#df3.head()

In [104]:
#df3.dropna()

In [107]:
df_n = df2.select_dtypes(include = [np.number])
df_l = df_n.loc[:,['HUMI','TEMP']]
df_l.shape

(19062, 2)

In [109]:
x = np.array(df_l['HUMI']).reshape(19062,1)
y = np.array(df_l['TEMP']).reshape(19062,1)
x
y

array([[ 1.],
       [ 5.],
       [ 8.],
       ...,
       [-2.],
       [-6.],
       [-6.]])

In [110]:
from sklearn.model_selection import train_test_split
from sklearn import datasets, linear_model
from sklearn.linear_model import LinearRegression

In [111]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.30)
print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(13343, 1) (13343, 1)
(5719, 1) (5719, 1)


In [112]:
reg = LinearRegression()
reg.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [113]:
reg.coef_

array([[0.04787932]])

In [114]:
reg.intercept_

array([11.61726577])

In [115]:
Y_pred = reg.predict(X_test)
Y_pred

array([[13.9633523 ],
       [15.78276635],
       [13.19728323],
       ...,
       [15.35185249],
       [12.95788664],
       [15.73488703]])

In [116]:
a = pd.DataFrame({"actual":list(X_test), "pred":list(Y_pred)})
a.head()

actual                  pred
0  [49.0]  [13.963352301222937]
1  [87.0]  [15.782766347741687]
2  [33.0]  [13.197283229004514]
3  [88.0]  [15.830645664755338]
4  [22.0]   [12.67061074185435]